version: '3.9'

services:

  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db_value:/var/lib/postgresql/data/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    container_name: backend
    build: ../
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    restart: always
    command: >
      sh -c "alembic upgrade head &&
             uvicorn legsy.main:app --host 0.0.0.0 --port 8000"


volumes:
  db_value:
