"""empty message

Revision ID: 162f2013fb93
Revises: 
Create Date: 2023-04-29 15:19:52.343302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162f2013fb93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('site_brand_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_table('color',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('size',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('good',
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedbacks', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='fk_good_brand'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nm_id')
    )
    op.create_table('goodcolor',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], name='fk_goodcolor_color_id'),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], name='fk_goodcolor_good_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('good_id', 'color_id', name='unique_good_color')
    )
    op.create_table('goodsize',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], name='fk_goodsize_good_id'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], name='fk_goodsize_size_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('good_id', 'size_id', name='unique_good_size')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goodsize')
    op.drop_table('goodcolor')
    op.drop_table('good')
    op.drop_table('size')
    op.drop_table('color')
    op.drop_table('brand')
    # ### end Alembic commands ###
